# Generated by Django 5.1.4 on 2026-06-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد')),
                ('discount_type', models.CharField(choices=[('percent', 'درصدی'), ('fixed', 'مبلغ ثابت')], default='percent', max_length=10, verbose_name='نوع')),
                ('percent', models.IntegerField(default=0, verbose_name='درصد تخفیف')),
                ('amount', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ تخفیف (تومان)')),
                ('min_order', models.PositiveBigIntegerField(default=0, verbose_name='حداقل سفارش')),
                ('max_uses', models.IntegerField(blank=True, null=True, verbose_name='حداکثر استفاده')),
                ('used_count', models.IntegerField(default=0, verbose_name='دفعات استفاده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
    ]
