# Generated by Django 5.1.4 on 2026-06-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='نشانک')),
                ('excerpt', models.TextField(verbose_name='خلاصه')),
                ('content', models.TextField(blank=True, verbose_name='محتوا')),
                ('cover', models.CharField(blank=True, default='', max_length=500, verbose_name='تصویر')),
                ('author', models.CharField(default='تیم اینتل شاپ', max_length=100, verbose_name='نویسنده')),
                ('category', models.CharField(blank=True, default='', max_length=50, verbose_name='دسته\u200cبندی')),
                ('read_time', models.CharField(blank=True, default='', max_length=20, verbose_name='زمان مطالعه')),
                ('jalali_date', models.CharField(blank=True, default='', max_length=20, verbose_name='تاریخ انتشار (جلالی)')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات بلاگ',
                'ordering': ['-created_at'],
            },
        ),
    ]
