# Generated by Django 5.1.4 on 2026-06-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='درباره اینتل شاپ', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('story_title', models.CharField(default='داستان ما', max_length=200)),
                ('story_body', models.TextField(blank=True)),
                ('why_title', models.CharField(default='چرا اینتل شاپ؟', max_length=200)),
                ('why_items', models.JSONField(blank=True, default=list, verbose_name='موارد فهرست (لیست متن)')),
                ('stats', models.JSONField(blank=True, default=list, verbose_name='آمارها (لیست {label,value,icon})')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'صفحه درباره ما',
                'verbose_name_plural': 'صفحه درباره ما',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('read', 'خوانده\u200cشده'), ('replied', 'پاسخ داده\u200cشده'), ('archived', 'بایگانی')], default='new', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='زیرعنوان')),
                ('badge', models.CharField(blank=True, max_length=80, verbose_name='برچسب بالا')),
                ('offer', models.CharField(blank=True, max_length=80, verbose_name='برچسب پیشنهاد')),
                ('cta_label', models.CharField(blank=True, max_length=80, verbose_name='متن دکمه')),
                ('cta_link', models.CharField(blank=True, max_length=300, verbose_name='لینک دکمه')),
                ('image', models.CharField(blank=True, max_length=500, verbose_name='تصویر (URL یا مسیر مدیا)')),
                ('gradient', models.CharField(choices=[('primary', 'آبی پررنگ (پیش\u200cفرض)'), ('amber', 'کهربایی'), ('violet', 'بنفش'), ('emerald', 'سبز زمردی'), ('rose', 'صورتی')], default='primary', max_length=20, verbose_name='پالت رنگی')),
                ('chips', models.JSONField(blank=True, default=list, verbose_name='چیپس\u200cها (لیست متن)')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'اسلاید بنر',
                'verbose_name_plural': 'اسلایدهای بنر',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'مشترک خبرنامه',
                'verbose_name_plural': 'مشترکین خبرنامه',
                'ordering': ['-created_at'],
            },
        ),
    ]
