# Generated by Django 5.1.4 on 2026-06-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('email', 'ایمیل'), ('phone', 'موبایل')], max_length=10)),
                ('value', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=6)),
                ('reset_token', models.CharField(blank=True, max_length=64)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'کد بازیابی رمز',
            },
        ),
    ]
