# Generated by Django 5.1.4 on 2026-06-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('register', 'تأیید ثبت\u200cنام'), ('reset', 'بازیابی رمز عبور')], max_length=10)),
                ('method', models.CharField(choices=[('email', 'ایمیل'), ('phone', 'موبایل')], max_length=10)),
                ('value', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=6)),
                ('proof_token', models.CharField(blank=True, max_length=64)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'کد یک\u200cبارمصرف',
                'verbose_name_plural': 'کدهای یک\u200cبارمصرف',
            },
        ),
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['purpose', 'method', 'value'], name='accounts_ot_purpose_ee3f3c_idx'),
        ),
    ]
