# Generated by Django 5.1.4 on 2026-06-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='اینتل شاپ', max_length=100, verbose_name='نام فروشگاه')),
                ('email', models.EmailField(default='info@intelshop.ir', max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='تلفن')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('free_shipping_enabled', models.BooleanField(default=True, verbose_name='ارسال رایگان')),
                ('free_shipping_over', models.PositiveBigIntegerField(default=5000000, verbose_name='حد ارسال رایگان')),
                ('express_enabled', models.BooleanField(default=True, verbose_name='ارسال اکسپرس')),
                ('payment_online', models.BooleanField(default=True, verbose_name='پرداخت آنلاین')),
                ('payment_cod', models.BooleanField(default=True, verbose_name='پرداخت در محل')),
                ('payment_installment', models.BooleanField(default=False, verbose_name='خرید اقساطی')),
                ('notify_new_order', models.BooleanField(default=True, verbose_name='سفارش جدید')),
                ('notify_low_stock', models.BooleanField(default=True, verbose_name='موجودی کم')),
                ('notify_new_user', models.BooleanField(default=False, verbose_name='کاربر جدید')),
            ],
            options={
                'verbose_name': 'تنظیمات فروشگاه',
                'verbose_name_plural': 'تنظیمات فروشگاه',
            },
        ),
    ]
