# Generated by Django 5.1.4 on 2026-06-18 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('condition', models.CharField(choices=[('new', 'نو'), ('used', 'دست دوم')], default='new', max_length=10, verbose_name='وضعیت')),
                ('warranty', models.CharField(blank=True, max_length=100, verbose_name='گارانتی')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت (تومان)')),
                ('discount_price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='امتیاز')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='تعداد نظر')),
                ('tags', models.JSONField(default=list, verbose_name='برچسب\u200cها')),
                ('featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand', verbose_name='برند')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(blank=True, max_length=100, verbose_name='پردازنده')),
                ('ram', models.CharField(blank=True, max_length=50, verbose_name='رم')),
                ('storage', models.CharField(blank=True, max_length=100, verbose_name='حافظه')),
                ('gpu', models.CharField(blank=True, max_length=100, verbose_name='پردازنده گرافیکی')),
                ('display', models.CharField(blank=True, max_length=100, verbose_name='نمایشگر')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='سیستم عامل')),
                ('weight', models.CharField(blank=True, max_length=50, verbose_name='وزن')),
                ('battery', models.CharField(blank=True, max_length=50, verbose_name='باتری')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='products.product')),
            ],
            options={
                'verbose_name': 'مشخصات فنی',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='امتیاز')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرها',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
    ]
