# Generated by Django 5.1.4 on 2026-06-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_review_status_reviewlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.JSONField(blank=True, default=list, verbose_name='رنگ\u200cبندی'),
        ),
    ]
